# permissions for end users to edit jwts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jwt-editor-role
rules:
- apiGroups:
  - tokens.hexhibit.xyz
  resources:
  - jwts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tokens.hexhibit.xyz
  resources:
  - jwts/status
  verbs:
  - get
